version: "3.8" 

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    ports:
      - "8096:8096"         # Jellyfin Web Interface
      - "7359:7359/udp"     # Network Discovery (must be UDP)
      
    volumes:
      - "C:/docker/jellyfin/server/config:/config"
      - "C:/docker/jellyfin/server/cache:/cache"
      - type: bind
        source: "G:/Movies"
        target: /media
      - type: bind
        source: "H:/FamilyFunction"
        target: /media2
        read_only: true
