# docker-compose.openwebui.yml
volumes:
  openwebui-data:
networks:
  demo:
services:
  open-webui:
    image: dyrnq/open-webui
    container_name: open-webui
    networks: ['demo']
    ports:
      - "3000:8080"
    volumes:
      - openwebui-data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
