version: '3.9'

volumes:
  jenkins_data:

networks:
  demo:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    networks:
      - demo
    ports:
      - "8081:8080"
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    volumes:
      - jenkins_data:/var/jenkins_home
