services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"         # Portainer Web Interface
    volumes:
      - "C:/docker/portainer/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  portainer_data:
networks:
  demo: